@startuml

!include https://raw.githubusercontent.com/Kyrales/1C-ER-plantuml/refs/heads/extended/main.puml

header V1
title ER диаграмма  системы



package НСИ <<folder>> {

    _Справочник(Организации, "Организации")
    _Справочник(Контрагенты, "Контрагенты")
    _Справочник(Склады, "Склады")
    _Справочник(Номенклатура, "Номенклатура"){
        ВидыТоваров
    }
    _Справочник(Валюты, "Валюты")
    _Справочник(ВидыЦен, "ВидыЦен")
    _Справочник(Пользователи, "Пользователи")
    _Справочник(РасчетныеСчета, "Расчетный счет")

    _Перечисление(ВидыТоваров, "Виды товаров"){
        Товар
        Услуга

    }

    _Перечисление(СостояниеЗаказа, "Состояния Заказов"){
        Открыт
        Вработе
        Выполнен
        Закрыт
    }
}

package Закупки <<folder>> {

    _Документ(ЗаказПоставщику, "Заказ поставщику") {
        Поставщик
        Склад
        Валюта
        ВидЦен
        Организация
        СостояниеЗаказа
        Автор
        Сумма
        -- Товары --
        Товар
        Цена
        Количество
        Сумма
    }

    _Документ(ПоступлениеТоваров, "Поступление товаров") {
        Поставщик
        Склад
        Валюта
        ВидЦен
        Организация
        Автор
        Сумма
        -- Товары --
        Товар
        Цена
        Количество
        Сумма
    }

     _РегистрНакопления(ТоварныеЗапасыЗакупка, "Товарные запасы") {
        <$d> Товар
        <$d> Склад

        <$r> Количество
    }

    _РегистрНакопления(ВзаиморасчетыЗакупка, "Взаиморасчеты") {
        <$d> Контрагент
        <$d> Валюта

        <$r> Сумма
    }

}
package Продажи <<folder>> {
    _Документ(ЗаказКлинета, "Заказ клиента") {
        Покупатель
        Склад
        Валюта
        ВидЦен
        Организация
        СостояниеЗаказа
        Автор
        Сумма
        -- Товары --
        Товар
        Цена
        Количество
        Сумма
    }

    _Документ(РеализацияТоваров, "реализация товаров") {
        Покупатель
        Склад
        Валюта
        ВидЦен
        Организация
        Автор
        Сумма
        -- Товары --
        Товар
        цена
        Количество
        Сумма
    }

    _РегистрНакопления(ТоварныеЗапасыПродажа, "Товарные запасы") {
        <$d> Товар
        <$d> Склад

        <$r> Количество
    }

    _РегистрНакопления(ВзаиморасчетыПродажа, "Взаиморасчеты") {
        <$d> Контрагент
        <$d> Валюта

        <$r> Сумма
    }

}

package Склад <<folder>> {

    _Документ(ЗаданиеНаПриёмку, "Задание на приёмку") {
        Склад
        Организация
        СостояниеЗаказа
        Автор
        -- Товары --
        Товар
        Количество

    }

    _Документ(ЗаданиеНаОтгрузку, "Задание на отгрузку") {
        Склад
        Организация
        СостояниеЗаказа
        Автор
        -- Товары --
        Товар
        Количество

    }

}

package Финансы <<folder>> {
    _Документ(Оплата, "Оплата") {
        Организация
        Сумма
        Валюта
        Контрагент
        РасчетныйСчет
    }

    _РегистрНакопления(ВзаиморасчетыОплата, "Взаиморасчеты") {
        <$d> Контрагент
        <$d> Валюта

        <$r> Сумма
    }

    ВидыТоваров--> Номенклатура::ВидыТоваров

    Организации--> ЗаказПоставщику::Организация
    Организации--> ПоступлениеТоваров::Организация
    Организации--> ЗаказКлинета::Организация
    Организации--> РеализацияТоваров::Организация
    Организации--> ЗаданиеНаПриёмку::Организация
    Организации--> ЗаданиеНаОтгрузку::Организация
    Организации--> Оплата::Организация

    Контрагенты--> ЗаказПоставщику::Поставщик
    Контрагенты--> ПоступлениеТоваров::Поставщик
    Контрагенты--> ЗаказКлинета::Покупатель
    Контрагенты--> РеализацияТоваров::Покупатель
    Контрагенты--> Оплата::Контрагент
    Контрагенты--> ВзаиморасчетыЗакупка::Контрагент
    Контрагенты--> ВзаиморасчетыПродажа::Контрагент
    Контрагенты--> ВзаиморасчетыОплата::Контрагент

    Склады--> ЗаказПоставщику::Склад
    Склады--> ПоступлениеТоваров::Склад
    Склады--> ЗаказКлинета::Склад
    Склады--> РеализацияТоваров::Склад
    Склады--> ЗаданиеНаПриёмку::Склад
    Склады--> ЗаданиеНаОтгрузку::Склад
    Склады--> ТоварныеЗапасыПродажа::Склад
    Склады--> ТоварныеЗапасыЗакупка::Склад

    РасчетныеСчета--> Оплата::РасчетныйСчет

    Валюты--> ЗаказПоставщику::Валюта
    Валюты--> ПоступлениеТоваров::Валюта
    Валюты--> ЗаказКлинета::Валюта
    Валюты--> РеализацияТоваров::Валюта
    Валюты--> Оплата::Валюта
    Валюты--> ВзаиморасчетыЗакупка::Валюта
    Валюты--> ВзаиморасчетыПродажа::Валюта
    Валюты--> ВзаиморасчетыОплата::Валюта

    Пользователи--> ЗаказПоставщику::Автор
    Пользователи--> ПоступлениеТоваров::Автор
    Пользователи--> ЗаказКлинета::Автор
    Пользователи--> РеализацияТоваров::Автор
    Пользователи--> ЗаданиеНаПриёмку::Автор
    Пользователи--> ЗаданиеНаОтгрузку::Автор
    Пользователи--> Оплата::Автор

    СостояниеЗаказа--> ЗаказКлинета::СостояниеЗаказа
    СостояниеЗаказа--> ЗаказПоставщику::СостояниеЗаказа
    СостояниеЗаказа--> ЗаданиеНаПриёмку::СостояниеЗаказа
    СостояниеЗаказа--> ЗаданиеНаОтгрузку::СостояниеЗаказа

    Номенклатура--> ЗаказПоставщику::Товар
    Номенклатура--> ПоступлениеТоваров::Товар
    Номенклатура--> ЗаказКлинета::Товар
    Номенклатура--> РеализацияТоваров::Товар
    Номенклатура--> ЗаданиеНаПриёмку::Товар
    Номенклатура--> ЗаданиеНаОтгрузку::Товар
    Номенклатура--> ТоварныеЗапасыПродажа::Товар
    Номенклатура--> ТоварныеЗапасыЗакупка:Товар

    ПоступлениеТоваров--> ТоварныеЗапасыЗакупка
    ПоступлениеТоваров--> ВзаиморасчетыЗакупка

    РеализацияТоваров--> ТоварныеЗапасыПродажа
    РеализацияТоваров--> ВзаиморасчетыПродажа

    Оплата--> ВзаиморасчетыОплата


    @enduml