@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


title Архитектура взаимодействия Торговой и Складской системы



' Системы
System_Boundary(1С_TS, "1C:Торговая система"){
   
    Container(Закупки, "Подсистема закупок", "") {
        Component(ЗаказПоставщику, "Заказ поставщику",, "")
        
         Component(Поступление, " Поступление товара",, "")
         
    } 

    
    Container(Продажа, "Подсистема продаж ", ""){
        Component(ЗаказПокупателя, "Заказ покупателя",, "")
        
         Component(Реализация, " Реализация товара",, "")
    } 
    
        Container(МодульВзаимодействияСWMS, "Модуль взаимодействия с складской системой", "") {
        
         
    } 
    
}
System_Boundary(БроккерСообщений, "Броккер cообщений(RabbitMQ)") 
System_Boundary(1С_WMS, "1С: Складская система") {
   
    Container(ОбработкаЗаказов, "Обработка заданий", "") {
    
    Component(ЗаданиеНаПриёмку, "Задания на приемку",, "")
        
    Component(ЗаданиеНаОтгрузку, "Задания на отгрузку",, "")
    } 
     Container(МодульВзаимодействияСTS, "Модуль взаимодействия с тороговой системой", "") {
        
         
    } 

 } 


' Связи



Rel(ЗаказПокупателя, МодульВзаимодействияСWMS, "Передача новых заказов клиента")
Rel(ЗаказПоставщику, МодульВзаимодействияСWMS, "Передача  новых заказов поставщику")
Rel(МодульВзаимодействияСWMS, БроккерСообщений, "Передача заданий на обработку в WMS")
Rel(БроккерСообщений, МодульВзаимодействияСTS, "Передача заданий на обработку в WMS")
Rel(МодульВзаимодействияСTS, ЗаданиеНаПриёмку, "Новых задания на приемку")
Rel(МодульВзаимодействияСTS, ЗаданиеНаОтгрузку, "Новые задания на отгрузку")
Rel(ЗаданиеНаОтгрузку, МодульВзаимодействияСTS, "Выполеннеые задания")
Rel(ЗаданиеНаПриёмку, МодульВзаимодействияСTS, "Выполеннеые задания")
Rel(МодульВзаимодействияСTS, БроккерСообщений, "Передача выполеннеых заданий в TS")
Rel(БроккерСообщений, МодульВзаимодействияСWMS, "Передача выполеннеых заданий в TS")
Rel(МодульВзаимодействияСWMS, Поступление, "Формирование поступлений")
Rel(МодульВзаимодействияСWMS, Реализация, "Формирование реализаций")




@enduml